---
on: [push, pull_request]
name: main

jobs:
  test:
    runs-on: ubuntu-latest
    container: alpine
    name: test

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          apk update && apk upgrade
          apk add make bash coreutils git neovim lua

      - name: run tests
        run: make test
